Controllers/AuthController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Admin.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SignIn()
        {
            ViewBag.Message = "NotAuthen";
            return View("~/Views/Shared/Auth/SignIn.cshtml");
        }
        [HttpPost]
        public IActionResult SignIn(string UserName, string Password)
        {
            User_Info zInfo = new User_Info(UserName, Password);
            if (zInfo.Code == "200")
            {
                ViewBag.Message = "IsAuthen";

                // Save
                var key = "UserLogged";
                var obj = JsonConvert.SerializeObject(zInfo.User);
                HttpContext.Session.SetString(key, obj);

                string url = Url.Action("Index", "Home");
                Redirect(url);
            }
            else
            {
                ViewBag.Message = "405";
            }

            return View("~/Views/Shared/Auth/SignIn.cshtml");
        }

        public IActionResult SignOut()
        {
            HttpContext.Session.Clear();
            return View("~/Views/Shared/Auth/SignIn.cshtml");
        }
    }
}

Views/Shared/_Layout.cshtml
@{
    string _LogoLeft = "~/assets/themes/img/Logo_TNS_new.png";
    string _LogoMain = "~/assets/themes/img/Logo_TNS.png";
}
<!DOCTYPE html>
<html class="fixed sidebar-light">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UI</title>
    <!-- Web Fonts  -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">
    <!-- Vendor CSS -->
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/bootstrap/css/bootstrap.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/animate/animate.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/font-awesome/css/all.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/jstree/themes/default/style.css")" />
    <!-- Specific Page Vendor CSS -->
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/jquery-ui/jquery-ui.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/jquery-ui/jquery-ui.theme.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/jquery-confirm/css/jquery-confirm.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/magnific-popup/magnific-popup.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/select2/css/select2.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/pnotify/pnotify.custom.css")" />
    <!-- Theme CSS -->
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/css/theme.css")" />
    <!-- Skin CSS -->
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/css/skins/default.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/site.css")" />
    <style>
        .modal-wrapper {
            padding: 0px !important;
        }
    </style>
    <!-- Head Libs -->
    <script src="@Url.Content("~/assets/themes/vendor/modernizr/modernizr.js")"></script>
</head>
<body>
    <section class="body">
        <header class="header">
            <div class="logo-container">
                <a href="#" class="logo">
                    <img src="@Url.Content(_LogoLeft)" style="height:35px;">
                </a>
                <div class="d-md-none toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
                    <i class="fas fa-bars" aria-label="Toggle sidebar"></i>
                </div>
            </div>
            <!-- start: search & user box -->
            <div class="header-right">

                <span class="separator"></span>
                <div id="userbox" class="userbox">
                    <a href="#" data-toggle="dropdown">
                        <figure class="profile-picture">
                            <img src="@Url.Content(_LogoMain)" alt="Joseph Doe" class="rounded-circle" data-lock-picture="img/!logged-user.jpg" style="object-fit:cover">
                        </figure>
                        <div class="profile-info" data-lock-name="John Doe" data-lock-email="..">
                            <span class="name">Quản lý</span>
                        </div>
                        <i class="fa custom-caret"></i>
                    </a>
                    <div class="dropdown-menu">
                        <ul class="list-unstyled mb-2">
                            <li>
                                <a role="menuitem" href="@Url.Action("SignOut","Auth")">
                                    <i class="fas fa-power-off"></i>
                                    Thoát tài khoản
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- end: search & user box -->
        </header>
        <div class="inner-wrapper" style="background-image: url('@Url.Content("#")')">
            <aside id="sidebar-left" class="sidebar-left" style="">
                <div class="sidebar-header">
                    <div class="sidebar-title">

                    </div>
                    <div class="sidebar-toggle d-none d-md-block" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
                        <i class="fas fa-bars" aria-label="Toggle sidebar"></i>
                    </div>
                </div>
                <div class="nano">
                    <div class="nano-content">
                        <nav id="menu" class="nav-main" role="navigation">
                            <ul class="nav nav-main">
                                <li>
                                    <a asp-controller="Home" asp-action="Role">
                                        <i class="far fa-circle"></i><span>1. Chức năng</span>
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="Home" asp-action="Partner">
                                        <i class="far fa-circle"></i><span>2. Khách hàng/ đối tác</span>
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="Home" asp-action="Role_Partner">
                                        <i class="far fa-circle"></i><span>3. Phân chức năng, đối tác</span>
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="Home" asp-action="Account">
                                        <i class="far fa-circle"></i><span>4. Tài khoản đối tác</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </aside>
            <section role="main" class="content-body">
                @RenderBody()
            </section>
        </div>
    </section>
    <partial name="_CookieConsentPartial" />
    <script src="@Url.Content("~/assets/themes/vendor/jquery/jquery.min.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/jquery-browser-mobile/jquery.browser.mobile.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/popper/umd/popper.min.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/bootstrap/js/bootstrap.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/common/common.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/nanoscroller/nanoscroller.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/magnific-popup/jquery.magnific-popup.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/moment/moment.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/jquery-confirm/js/jquery-confirm.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/pnotify/pnotify.custom.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/select2/js/select2.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/ios7-switch/ios7-switch.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/autosize/autosize.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/inputmask/jquery.inputmask.bundle.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/jquery-validation/jquery.validate.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/bootstrap-wizard/jquery.bootstrap.wizard.js")"></script>
    <script src="@Url.Content("~/assets/themes/js/jquery.number.js")"></script>
    <script src="@Url.Content("~/assets/themes/js/theme.js")"></script>
    <!-- Theme Initialization Files -->
    <script src="@Url.Content("~/assets/themes/js/theme.init.js")"></script>
    <script src="@Url.Content("~/js/Utils.js")"></script>
    <script src="@Url.Content("~/js/site.js")"></script>
    <script src="@Url.Content("~/js/tableHeadFixer.js")"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>